### ISSUE TITLE
Deployed Link is not proper.

### ISSUE THREAD

**Issue by mohitagrawal22** [ShaswatSRaghuvansi/unused-library-4088#23]
Add demo video link if deployed link is not available

**Comment by ShaswatSRaghuvansi** [comment]
I was waiting for the review sir, I will soon start my work on creating a
video on it and add it to my project.

Thanks & Regards
Shaswat Singh Raghuvansi

**Comment by ShaswatSRaghuvansi** [comment]
Demo video link (google drive) is added in the description and checked.
